### ISSUE TITLE
Cache Support

### ISSUE THREAD

**Issue by gpedro** [wejs/we-plugin-github#1]
A API V3 do Github possui algumas [limitações de requisições](https://developer.github.com/v3/#rate-limiting), onde diz: `For requests using Basic Authentication or OAuth, you can make up to 5,000 requests per hour.`.

Supondo que temos 300 pessoas acessando simultaneamente e que cada um tenha três abas abertas, já se foi +50% do Limite.

Não é emergencial, mas é algo que já tem que ser pensado para evitar que o plugin quebre.
### Soluções
- Cache na memória
- Cache em um banco KV (redis)
- Cache no FS

**Comment by albertosouza** [comment]
Acho q podemos usar um model e depois de criado dar apenas um update.
Usando um model depois podemos plugar outros recursos como o de flags, association  ou imagens

**Comment by gpedro** [comment]
pode ser. Também é preciso colocar um expireDate pra renovar os dados quando consultados. Quando a pessoa for buscar esses dados do banco, se o `expireDate > now`, ele vai na api e atualiza os dados no banco.

**Comment by albertosouza** [comment]
isso @leonanluppi acha que pode fazer isso?

**Comment by leonanluppi** [comment]
@albertosouza vou tentar fazer, qualquer coisa te grito!

**Comment by leonanluppi** [comment]
@albertosouza @gpedro podem olhar para ver se seria aquilo mesmo? qualquer help é bem-vindo!

**Comment by leonanluppi** [comment]
Tem que ver os campos necessários para o model. Se puderem ajudar nisso, coloquei somente o basico, caso precise adicionar mais algum só me dizer.

**Comment by gpedro** [comment]
boa garoto! :+1:
